name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          cache: true

      - name: Patch Flutter SDK
        run: |
          sed -i '918a\rect = rect.inflate(96);' ${{ env.FLUTTER_ROOT }}/packages/flutter/lib/src/rendering/viewport.dart

      - name: Get dependencies
        run: flutter pub get

      - name: Build Mobile APK
        run: flutter build apk --release --flavor mobile --split-per-abi

      - name: Build TV APK
        run: flutter build apk --release --flavor tv --target lib/main_tv.dart --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: kurdish-player-apks
          path: build/app/outputs/flutter-apk/app-*-release.apk
